### ISSUE TITLE
Review documentation creation process and add automation to it

### ISSUE THREAD

**Issue by gauthiermartin** [sonia-auv/documentation#10]
Review how we will generate our documentation,  it would be nice to have a repo template to generate project specific documentation and auto generate documentation on read the docs

**Comment by gauthiermartin** [comment]
Should we consider github wiki pages ?

https://guides.github.com/features/wikis/

**Comment by kevincharbonneau** [comment]
Ok so basically I have looked at the following tools : 

**Paid**
- [Confluence](www.atlassian.com/confluence)
- [Jive](https://www.jivesoftware.com/)
- [Slab](slab.com)
- [Documize](https://documize.com)

**Open-source / Free**
- [XWiki](http://www.xwiki.org/xwiki/bin/view/Main/WebHome)
- [Gollum](https://github.com/gollum/gollum)
- [Wiki.js](https://wiki.js.org/)

I believe that Paid solutions are either overkill or overpriced for the purpose they might serve. 

The question is now, would using simply github wikis for each github project be fine or would it be preferable to host a larger documentation ?

I think that the easiest solution would be to use a centralized documentation with a tool like **Wiki.js**.

**Comment by kevincharbonneau** [comment]
closing issue due to wikijs solution adopted https://github.com/sonia-auv/wiki-js/issues/1
