### ISSUE TITLE
Implement a git workflow procedure and document it properly

### ISSUE THREAD

**Issue by gauthiermartin** [sonia-auv/documentation#11]
Setup a internal procedure of our git workflow following the best practices 

(Jeter un coup d'oeil au GitFlow des étudiants de l'ÉTS chez JFortin)

[MET-GitFlow-160120-0324.pdf](https://github.com/sonia-auv/documentation/files/4069178/MET-GitFlow-160120-0324.pdf)

**Comment by gauthiermartin** [comment]
Here are two good article on the subject 

- https://medium.com/@negarjf/use-git-more-efficiently-a-simple-git-workflow-c4e650289ec8
- https://medium.com/@jurtzmarcel/git-workflows-cb0c023ca88

**Comment by gauthiermartin** [comment]
Here is my proposition on how we should setup our gitflow. Master should be a locked branch to user and should be updated only using by the CI/CD pipeline tool (TravisCI). Release Is the branch on which we are deploying a semver tagged version of the release. Hotfix would be done in this branch develop will be the branch where we we will merge new or updated feature and finally feature branch will be the base of all new feature or update on an module ! @coumarc9 and @kevincharbonneau Could you comment on your toughts about the process and give feedback or ideas if you have !

**Comment by marcantoinecouture** [comment]
I think it's a good idea to establish a workflow for development. 
The only problem I can see is that it must not be too difficult to do some hot fix while we are in a test or at San Diego (including local deployment).
I think we should also establish a "default" branch for each node using the same name. When you have finished testing and you have to fix your code, you must change the repository branch, so other members can continue to test on the submarine.  Summary: when you have finished testing and your code doesn't work, you bring your repository node to default.

**Comment by gauthiermartin** [comment]
Since we did not figure out yet how we will work with the docker images (1 image with all repo in it or 1 image per repo, ....) I think we should have a basic gitflow workflow implemented at first so everyone get use to it and respect it we could have this one to be the V1 and then when will have the docker image sorted out we will adapt from the V1 gitflow to the V2  @coumarc9  and @kevincharbonneau  What do you think

**Comment by kevincharbonneau** [comment]
@gauthiermartin Just read the first draft of http://10.214.96.76:4081/gitflow-and-development-workflow 

Corrected most of the syntax and grammar.

Some sentences might need to be reviewed.

For example, I'm uncertain of what we mean here:
> This is our Gitflow methodology since following our recent process review

**Comment by kevincharbonneau** [comment]
Also, I'd recommend using a few hyperlinks in the documentation. For example, when we talk about PRs it'd be useful to have a hyperlink to GitHub's or Atlassian's documentation on the subject !

**Comment by gauthiermartin** [comment]
@kevincharbonneau  I was planing on documenting PR and Issues since we have our own templates

**Comment by gauthiermartin** [comment]
Completed
