### ISSUE TITLE
Create project board in every repo

### ISSUE THREAD

**Issue by gauthiermartin** [sonia-auv/documentation#15]

**Comment by gauthiermartin** [comment]
Project boards have been created in almost all repos except the following : 

Hardware Firmware (renamed repo following convention):
- https://github.com/sonia-auv/Firmware_ESC_19
- https://github.com/sonia-auv/FirmwareELE_PSU_2019
- https://github.com/sonia-auv/Firmware_utility
- https://github.com/sonia-auv/Firmware_template
- https://github.com/sonia-auv/interface_RS485/ 
- https://github.com/sonia-auv/firmware_io_control  (Still Used ?)
- https://github.com/sonia-auv/firmware_io_control (Still Used ?)
- https://github.com/sonia-auv/firmware_esc 
- https://github.com/sonia-auv/firmware_io_control 
- https://github.com/sonia-auv/firmware_power_supply
- https://github.com/sonia-auv/fpga_hydrophones  (Still Used ?)
- https://github.com/sonia-auv/firmware_ura
- https://github.com/sonia-auv/firmware_killmission_switches  (Still Used ?)
- https://github.com/sonia-auv/sonia_firmware_scripts  (Still Used ?)
- https://github.com/sonia-auv/firmware_control (Still Used ?)
- https://github.com/sonia-auv/sonia_firmware_lib (Still Used ?)

ROS Components:
- https://github.com/sonia-auv/lib_atlas (Still Used ?)
- https://github.com/sonia-auv/gazebo_simulation (Still Used ?)
- https://github.com/sonia-auv/provider_luxmeter (Still Used ?)
- https://github.com/sonia-auv/provider_kill_mission (Still Used ?)
- https://github.com/sonia-auv/provider_keypad (Still Used ?)

Other App or Module :
- https://github.com/sonia-auv/auv-simulator (Still Used ?)
- https://github.com/sonia-auv/sonia-web-app  (Still Used ?)
- https://github.com/sonia-auv/telemetry_web (Still Used ?)
- 

These need to be renamed following convention (no docker in name):
- https://github.com/sonia-auv/docker-ros-airflow
- https://github.com/sonia-auv/docker-labelbox-exporter
- https://github.com/sonia-auv/docker-ros-bag-extractor

**Comment by gauthiermartin** [comment]
This repo will need to be removed / renamed after we completed Airflow pipeline development

-  https://github.com/sonia-auv/deep-detector-model

**Comment by Kam0ss** [comment]
> Project boards have been created in almost all repos except the following :
> 
> Hardware Firmware (renamed repo following convention):
> 
>     * https://github.com/sonia-auv/Firmware_ESC_19
> 
>     * https://github.com/sonia-auv/FirmwareELE_PSU_2019
> 
>     * https://github.com/sonia-auv/Firmware_utility
> 
>     * https://github.com/sonia-auv/Firmware_template
> 
>     * https://github.com/sonia-auv/interface_RS485/
> 
>     * https://github.com/sonia-auv/firmware_io_control  (Still Used ?)
> 
>     * https://github.com/sonia-auv/firmware_io_control (Still Used ?)
> 
>     * https://github.com/sonia-auv/firmware_esc
> 
>     * https://github.com/sonia-auv/firmware_io_control
> 
>     * https://github.com/sonia-auv/firmware_power_supply
> 
>     * https://github.com/sonia-auv/fpga_hydrophones  (Still Used ?)
> 
>     * https://github.com/sonia-auv/firmware_ura
> 
>     * https://github.com/sonia-auv/firmware_killmission_switches  (Still Used ?)
> 
>     * https://github.com/sonia-auv/sonia_firmware_scripts  (Still Used ?)
> 
>     * https://github.com/sonia-auv/firmware_control (Still Used ?)
> 
>     * https://github.com/sonia-auv/sonia_firmware_lib (Still Used ?)
> 
> 
> ROS Components:
> 
>     * https://github.com/sonia-auv/lib_atlas (Still Used ?)
> 
>     * https://github.com/sonia-auv/gazebo_simulation (Still Used ?)
> 
>     * https://github.com/sonia-auv/provider_luxmeter (Still Used ?)
> 
>     * https://github.com/sonia-auv/provider_kill_mission (Still Used ?)
> 
>     * https://github.com/sonia-auv/provider_keypad (Still Used ?)
> 
> 
> Other App or Module :
> 
>     * https://github.com/sonia-auv/auv-simulator (Still Used ?)
> 
>     * https://github.com/sonia-auv/sonia-web-app  (Still Used ?)
> 
>     * https://github.com/sonia-auv/telemetry_web (Still Used ?)
> 
> 
> These need to be renamed following convention (no docker in name):
> 
>     * https://github.com/sonia-auv/docker-ros-airflow
> 
>     * https://github.com/sonia-auv/docker-labelbox-exporter
> 
>     * https://github.com/sonia-auv/docker-ros-bag-extractor

lib_atlas used in proc_image_processing : config.h 
gazebo_simulation not used yet but soon to be used

**Comment by gauthiermartin** [comment]
@Kam0ss Ok ! I Have added Projet Boards to both of them !

**Comment by gauthiermartin** [comment]
Project boards have been created in almost all repos except the following : 

Hardware Firmware (renamed repo following convention):
- [X] https://github.com/sonia-auv/Firmware_ESC_19 (Used)
- [X] https://github.com/sonia-auv/FirmwareELE_PSU_2019 (Used)
- [X] https://github.com/sonia-auv/Firmware_utility (Used)
- [X] https://github.com/sonia-auv/Firmware_template (Used)
- [X] https://github.com/sonia-auv/interface_RS485/ (Used)
- [X] https://github.com/sonia-auv/firmware_io_control  (Archived)
- [X] https://github.com/sonia-auv/firmware_io_control (Archived)
- [X] https://github.com/sonia-auv/firmware_esc (Archived)
- [X] https://github.com/sonia-auv/firmware_io_control (Archived)
- [X] https://github.com/sonia-auv/firmware_power_supply (Archived)
- [X] https://github.com/sonia-auv/fpga_hydrophones  (Archived)
- [X] https://github.com/sonia-auv/firmware_ura (Archived)
- [X] https://github.com/sonia-auv/firmware_killmission_switches  (Archived)
- [X] https://github.com/sonia-auv/sonia_firmware_scripts  (Archived)
- [X] https://github.com/sonia-auv/firmware_control (Archived)
- [X] https://github.com/sonia-auv/sonia_firmware_lib (Archived)

ROS Components:
- [X] https://github.com/sonia-auv/lib_atlas (Used + Project Board Created)
- [X] https://github.com/sonia-auv/gazebo_simulation (Used + Project Board Created)
- [] https://github.com/sonia-auv/provider_luxmeter (Used ?)
- [X] https://github.com/sonia-auv/provider_kill_mission (Used)
- [X] https://github.com/sonia-auv/provider_keypad (Used)

Other App or Module :
- [X] https://github.com/sonia-auv/auv-simulator (Archived)
- [X] https://github.com/sonia-auv/sonia-web-app  (Archived)
- [X] https://github.com/sonia-auv/telemetry_web (Removed)

These need to be renamed following convention (no docker in name):
- [] https://github.com/sonia-auv/docker-ros-airflow
- [] https://github.com/sonia-auv/docker-labelbox-exporter
- [] https://github.com/sonia-auv/docker-ros-bag-extractor

**Comment by gauthiermartin** [comment]
These need to be renamed following convention (no docker in name):

[x] https://github.com/sonia-auv/docker-ros-airflow (renamed to airflow-etl)
[x] https://github.com/sonia-auv/docker-labelbox-exporter (renamed to labelbox-exporter)
[x] https://github.com/sonia-auv/docker-ros-bag-extractor (renamed ros-bag-extractor)

**Comment by gauthiermartin** [comment]
ROS Components:

[x]https://github.com/sonia-auv/lib_atlas (Used + Project Board Created)
[x] https://github.com/sonia-auv/gazebo_simulation (Used + Project Board Created)
[x] https://github.com/sonia-auv/provider_luxmeter (Archived)
[x]https://github.com/sonia-auv/provider_kill_mission (Used)
[x] https://github.com/sonia-auv/provider_keypad (Used)

**Comment by gauthiermartin** [comment]
All project were renamed correctly. Project who where not active anymore have been archived and all active repo have an active project board
