### ISSUE TITLE
Investigate github actions and github packages

### ISSUE THREAD

**Issue by gauthiermartin** [sonia-auv/documentation#17]

**Comment by gauthiermartin** [comment]
We have made some investigation on github actions here are the results:

Pros:

-  A lot of features
-  Direct integration with Github
-  Active development

Cons:

- Not yet mature
- Longer build time
- To much options (might be complicated for other team member)


We have decided to keep our CI/CD with Travis-CI

**Comment by kevincharbonneau** [comment]
LGTM 👍 
don't forget to add your explanation the the technology stack page : http://70.83.115.43:4081/technology-stack
