### ISSUE TITLE
Cleanup Lucidchart folder in SONIA's google drive

### ISSUE THREAD

**Issue by gauthiermartin** [sonia-auv/documentation#20]

**Comment by gauthiermartin** [comment]
https://drive.google.com/drive/u/2/folders/0By7u6e_eWKuuMEtqUWtMNHotbzQ
https://www.lucidchart.com/documents#docs?folder_id=home&browser=icon

**Comment by marcantoinecouture** [comment]
I'll take a look a this later

**Comment by sonia-auv-master** [comment]
Clean up has been completed an we are now accessing our lucidchart documents directly from lucidchart not from the google drive !
