### ISSUE TITLE
Review repository naming convention

### ISSUE THREAD

**Issue by gauthiermartin** [sonia-auv/documentation#24]

**Comment by gauthiermartin** [comment]
This is completed at https://wiki.sonia.etsmtl.ca/en/workflow/repository-naming-convention

**Comment by marcantoinecouture** [comment]
I think we should add more info on ROS packages. Repo should be named with `provider`, `proc`, `controller` or `interface` as prefix

**Comment by gauthiermartin** [comment]
@coumarc9  I modified the documentation according to you last reply

**Comment by marcantoinecouture** [comment]
Perfect. I think we should take a look at this convention with the whole team at our next meeting.

**Comment by kevincharbonneau** [comment]
LGTM 👍
