### ISSUE TITLE
Problem referencing file in issue

### ISSUE THREAD

**Issue by marcantoinecouture** [sonia-auv/documentation#25]
##  Expected Behavior

On a file on Github, I want to reference a file in a issue with the "3 dots" on the file in the explorer

## Current Behavior

Issue template selection appears, after a selection, the file is not referenced

## Possible Solution

Unknown

## Comments

Thank you!

**Comment by marcantoinecouture** [comment]
@gauthiermartin @kevincharbonneau , I think this issue is for you

**Comment by kevincharbonneau** [comment]
@coumarc9 I not sure this is a **Priority: High** issue. 

The problem with this is that to allow this feature (3 dots leading to an Issue) we would need to disable the enforcing of the issue templates. This would potentially lead to people not using the templates.

Also, it's fairly easy to reference one (or multiple) line(s) of code to an Issue by simply copying the permalink of the line of code. like this : 
![image](https://user-images.githubusercontent.com/31851958/74351858-b2901e80-4d85-11ea-98ad-aab3e1328e06.png)

@gauthiermartin what do you think ?

**Comment by gauthiermartin** [comment]
This should be set to a medium - low priority since has @kevincharbonneau  has pointed out it's fairly easy to copy a permalink. We could investigate if it's possible to handle this use case with templated Issue Template

**Comment by marcantoinecouture** [comment]
I had set the issue to high because it may not help users to use/create issues. Since we have a work around, I agree we can set it to low, but we need to continue investigating our options.

**Comment by gauthiermartin** [comment]
We have investigated this issue and it's seem that there is not any option to have both Issue template and create issue from code option. We will then close this issue for now
