### ISSUE TITLE
Impossible to link more than 2 projects (repo) to an issue

### ISSUE THREAD

**Issue by Kam0ss** [sonia-auv/documentation#27]
When trying to add a project to an issue, it is impossible to add more than one repo.

**Comment by gauthiermartin** [comment]
We could consider doing project at orgranisation level https://github.com/dear-github/dear-github

**Comment by gauthiermartin** [comment]
It's not possible by default to add more then one repo we would need to create multiple project at organisation level !

**Comment by gauthiermartin** [comment]
@Kam0ss  Tasks should be scoped properly to fit issue for a specific repo .... you might need to scoped you task to be more representative of required changes for a specific repo
